version: '3.8'
services:
  frontend:
    build: ./frontend # Chemin vers le Dockerfile du frontend
    ports:
      - "3000:3000" # Port du frontend
    depends_on:
      - backend
    volumes:
    - ./frontend:/usr/src/app/
    - front_node_modules:/usr/src/app/node_modules
  backend:
    build: ./backend # Chemin vers le Dockerfile du backend
    ports:
      - "5000:5000" # Port du backend
    depends_on:
      - postgres
    volumes:
    - ./backend:/usr/src/app/
    - back_node_modules:/usr/src/app/node_modules
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_SERVER_PORT}:${POSTGRES_SERVER_PORT}
    volumes:
    - postgres-data:/var/lib/postgresql/data

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - "${PG_ADMIN_PORT}:80"
    depends_on:
      - postgres
volumes: 
  postgres-data:
  back_node_modules:
  front_node_modules: